package com.sample
 
import com.onlineapplication.kie.model.Message;
import com.onlineapplication.mvc.bean.Course;

rule "Bengali Honours"
	when
		m : Message( marksMap["BNG"] > 80 && marksMap["ENG"] > 40)
	then
		System.out.println( "Pass" );
		Course c = new Course();
		c.setCourseName("Bengali Honours");
		c.setCourseCode("BNGH");
		m.getSubjectList().add(c);		
end
rule "English Honours"
	when
		m : Message( marksMap["ENG"] > 80 && marksMap["BNG"] > 40)
	then
		System.out.println( "Pass" );
		Course c = new Course();
		c.setCourseName("English Honours");
		c.setCourseCode("ENGH");
		m.getSubjectList().add(c);		
end